try:
    with open("addr1.data","r") as rp:
        print("initially the index of rp :",rp.tell())
        fdata=rp.read(5)
        print("File data = ",fdata)
        print("now the index of rp :",rp.tell())
        fdata=rp.read(21)
        print("file data = ",fdata)
        print("now the index of rp :",rp.tell())
        fdata=rp.read(32)
        print("file data = ",fdata)
        print("now the index of the rp :",rp.tell())
        fdata=rp.read()
        print("--------file remaining data------------")
        print("file data = ",fdata)
        print("now the index of rp :",rp.tell())
        print("-"*40)
        print("file data = ",rp.read())
        print("-"*40)
        rp.seek(0)
        print("now the index of rp at :",rp.tell())
        print("file data = ",rp.read(15))
        print("now the index of rp :",rp.tell())
except FileNotFoundError:
    print("this file does not exist")
